# Generated by Django 4.2.6 on 2023-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='games',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='picture'),
        ),
    ]
